version: "3.1"

services:
  postgresql:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # adminer is a simple frontend for you to interact with the database
  adminer:
    image: adminer
    ports:
      - 8081:8081
